- src: git+https://github.com/paradigmadigital/create-ami
  version: v0.1
- src: git+https://github.com/paradigmadigital/create-instance
  version: v0.1
- src: git+https://github.com/paradigmadigital/create-tag
  version: v0.1
- src: git+https://github.com/paradigmadigital/find-ami
  version: v0.1
- src: git+https://github.com/paradigmadigital/terminate-ec2
  version: v0.1
- src: git+https://github.com/paradigmadigital/upgrade-all
  version: v0.1
