- src: git+git@git.paradigmadigital.com:ansible/create-ami
  version: develop
- src: git+git@git.paradigmadigital.com:ansible/create-instance
- src: git+git@git.paradigmadigital.com:ansible/create-tag
- src: git+git@git.paradigmadigital.com:ansible/find-ami
- src: git+git@git.paradigmadigital.com:ansible/terminate-ec2
- src: git+git@git.paradigmadigital.com:ansible/upgrade-all
